### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by MapperD** [BoltsJ/hex-size-support#2]
This module doesn't seem to play well with Z-Scatter. Causes the boarder to appear offset from the token to the top and left.
Also with Alternative Token Visibility active, selecting a token causes the screen to freeze requiring a reload.

Foundry 12

Testing this in a few games systems D&D5, Harnmaster and Cthulhu all seem to have the same result. Things work fine with a grid map but gridless maps cause this behavior

**Comment by BoltsJ** [comment]
This is a problem with those modules incorrectly assuming that the token shape is either a pixi Rectangle or pixi Polygon. The [API docs](https://foundryvtt.com/api/classes/client.Token.html#shape) specify that Token#shape can be a Rectangle, Polygon OR a Circle.
